### ISSUE TITLE
Missing HTTPS

### ISSUE THREAD

**Issue by manuGil** [sara-nl/spiderdocs#24]
Modern search engines (Google) don't index websites that don't use HTTPS. This makes the documentation website about Spider more difficult to find. 
**Can you enable HTTPS  on this domain http://doc.spider.surfsara.nl/?**

**Comment by oonkjbr** [comment]
Hi Manuel,
Thanks and good point. This url actually links to https://spiderdocs.readthedocs.io/en/latest/ , but I'll contact my colleagues to see if we can update the other url as well to https. @natalieda can you have a look at this?

**Comment by lnauta** [comment]
This issue is resolved, I'm closing it.
